// Describing ACTION NAMES
// ADD
export const ADD_PLAYER1_MOVE = "ADD_PLAYER1_MOVE";
export const ADD_PLAYER2_MOVE = "ADD_PLAYER2_MOVE";
export const ADD_WINNING_SCENARIO = "ADD_WINNING_SCENARIO";

// CREATE
export const CREATE_BOARD = "CREATE_BOARD";

// REMOVE
export const REMOVE_BOARD = "REMOVE_BOARD";

// CLEAR
export const CLEAR_PLAYER_POSITIONS = "CLEAR_PLAYER_POSITIONS";
export const CLEAR_WINNING_SCENARIOS = "CLEAR_WINNING_SCENARIOS";
export const CLEAR_BOARD = "CLEAR_BOARD";